### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by vdh** [elementalui/elemental-dist#2]
Could you please publish this on NPM? I'd prefer to keep Bower out of my dependencies.

**Comment by nkbt** [comment]
Use main lib for npm. This one is a temporary only for bower.

**Comment by nkbt** [comment]
Just in case: https://www.npmjs.com/package/elemental

``` bash
npm install --save elemental
```

**Comment by vdh** [comment]
I am using the main lib, but it doesn't contain a distributable version of the elemental.css file for some reason?

**Comment by nkbt** [comment]
@vdh it is not supposed to be there. When you use an npm lib you just require whatever you need from elemental package (like `const { Col, Container, Row } = require('elemental');`). You need some build process in place though. Browserify, Webpack, etc. As soon as you use React you already should have one in place, so your app will be bundled properly.

**Comment by vdh** [comment]
@nkbt But I'm using `node-sass`, not `less` for stylesheet pre-processing. It seems counter-intuitive to need a second CSS pre-processor just to build a library's CSS file.

`less` is also not declared in either the `dependencies` or the `devDependencies`. So is it a required dependency or isn't it?

**Comment by jossmac** [comment]
@vdh regarding less/sass it's something we're looking to address with JSS, please see elementalui/elemental#53

**Comment by nkbt** [comment]
@vdh with webpack you need to add one more loader, and that would fix it. What does your build process look like?

**Comment by vdh** [comment]
@nkbt I'm using Webpack. It's not about if I _could_ use something like `less-loader` to build the CSS, I definitely _could_ do that, but my problems are:
1) It forces me add LESS as a second redundant pre-processor dependency just to get up and running with the basic stylesheet, even if I don't want to customise Elemental UI's styles.
2) This build dependency isn't listed in the `package.json`, and not very clearly indicated in the setup instructions. It's only mentioned briefly on the Elemental UI home page, and the NPM package doesn't actually work out of the box without it.

**Comment by nkbt** [comment]
You are right, at the moment ElementalUI has some assumptions on the build process, and it is currently under active development. 

Full dist (no compile step, for browsers) is not completely working at the moment and there is an issue for that: https://github.com/elementalui/elemental/issues/118

Styling issue is there too as pointed by Joss.

Shipping the build in NPM package looks like a good temporary (until styling and better packaging is solved) solution to me and worth raising.
